[package]
name = "otel-tracing"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
viz = { path = "../../../viz", features = ["otel-tracing"] }

tokio = { workspace = true, features = [ "rt-multi-thread", "macros" ] }
opentelemetry.workspace = true
opentelemetry-jaeger = { version = "0.17.0", features = ["rt-tokio-current-thread"]}
