[package]
name = "otel-tracing"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
viz = { path = "../../../viz", features = ["otel-tracing"] }

tokio = { version = "1.0", features = [
  "rt-multi-thread",
  "macros",
] }
opentelemetry = "0.20.0"
opentelemetry-jaeger = { version = "0.19.0", features = ["rt-tokio-current-thread"]}
