[package]
name = "viz-core"
version = "0.1.2"
authors = ["Fangdun Tsai <cfddream@gmail.com>"]
description = "Viz Core"
license = "MIT OR Apache-2.0"
edition = "2021"

[features]
default = ["private-cookies"]

private-cookies = ["cookie/private"]
signed-cookies = ["cookie/signed"]

sse = ["tokio/time"]
ws = ["tokio/rt", "tokio-tungstenite", "pin-project"]
fs = ["mime-db", "tokio-util/io"]

[dependencies]
viz-utils = { path = "../viz-utils", version = "0.1.2" }

handle = "1.0"
form-data = "0.3"

bytes = "1.1"
http = "0.2"
headers = "0.3"
mime = "0.3"
toml = "0.5"
hyper = { version = "0.14", features = ["stream"] }
serde = { version = "1.0", features = ["derive"] }
cookie = { version = "0.15", default-features = false, features = [
  "percent-encode",
  "key-expansion",
] }

tokio = { version = "1.13", default-features = false, features = [
  "rt",
  "time",
  "fs",
], optional = true }
tokio-tungstenite = { version = "0.17", optional = true }
tokio-util = { version = "0.6", features = ["io"], optional = true }
pin-project = { version = "1.0", optional = true }
mime-db = { version = "1.6", optional = true }

[dev-dependencies]
futures-executor = "0.3"
