[package]
name = "viz-core"
version = "0.3.1"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Fangdun Tsai <cfddream@gmail.com>"]
categories = ["asynchronous", "network-programming", "web-programming"]
homepage = "https://viz.rs"
repository = "https://github.com/viz-rs/viz"
documentation = "https://docs.rs/viz"
description = "The core traits and types in for the `viz`."
publish = true

[features]
default = [
  "state",
  "limits",
  "params",
  "json",
  "form",
  "query",
  "multipart",
  "websocket",
  "cookie",
  "session",
]

state = []
limits = []

params = ["serde"]
json = ["serde", "serde_json"]
form = ["serde", "serde_urlencoded"]
query = ["serde", "serde_urlencoded"]
multipart = ["form-data"]
websocket = ["tokio/rt", "tokio-tungstenite"]
sse = ["tokio/time", "tokio-stream", "tokio-util"]

cookie = ["libcookie"]
cookie-private = ["cookie", "libcookie/private"]
cookie-signed = ["cookie", "libcookie/signed"]

session = ["cookie", "json", "sessions-core"]

csrf = ["cookie", "base64", "getrandom"]
cors = []

[dependencies]
thiserror = "1.0.31"
async-trait = "0.1.56"
dyn-clone = "1.0.8"
http = "0.2.7"
headers = "0.3.7"
http-body = "0.4.5"
hyper = { version = "0.14", features = ["stream"] }
mime = "0.3.16"
bytes = "1.1"
futures-util = "0.3.23"

serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
serde_urlencoded = { version = "0.7", optional = true }
form-data = { version = "0.4.1", optional = true }
sessions-core = { version = "0.3.4", optional = true }
libcookie = { package = "cookie", version = "0.16.0", features = [
  "percent-encode",
], optional = true }

# CSRF
getrandom = { version = "0.2.7", optional = true }
base64 = { version = "0.13.0", optional = true }

tokio = { version = "1.20", optional = true }
tokio-tungstenite = { version = "0.17.2", optional = true }
# TODO: EmbedHandler
rust-embed = { version = "6.4", optional = true }
tokio-stream = { version = "0.1.9", optional = true }
tokio-util = { version = "0.7.3", optional = true }

[dev-dependencies]
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
trybuild = "1.0.63"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
