[package]
name = "viz-handlers"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Fangdun Tsai <cfddream@gmail.com>"]
homepage = "https://viz.rs"
repository = "https://github.com/viz-rs/viz"
documentation = "https://docs.rs/viz-handlers"
description = "Viz handlers"
publish = false

[features]
default = ["serve"]

serve = [
  "mime_guess",
  "percent-encoding",
  "tokio-stream",
  "tokio-util/io",
  "tokio/fs",
  "tokio/io-util",
]

[dependencies]
viz-core = { path = "../viz-core", version = '0.3' }

# required!
thiserror = "1.0"

percent-encoding = { version = "2.1.0", optional = true }
mime_guess = { version = "2.0", optional = true }
tokio = { version = "1.20", optional = true }
tokio-stream = { version = "0.1.9", optional = true }
tokio-util = { version = "0.7.3", optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
