[package]
name = "embed"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
viz = { path = "../../../viz", features = ["embed"] }

tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
rust-embed.workspace = true
