[package]
name = "embed"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
viz = { path = "../../../viz", features = ["embed"] }

tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
rust-embed = "6.4.0"
