[package]
name = "form"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
viz = { path = "../../../viz" }

serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = [
  "rt-multi-thread",
  "macros",
] }
