[package]
name = "compression"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
viz = { path = "../../viz", features = ["compression"] }

tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
