[package]
name = "compression"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
viz = { path = "../../viz", features = ["compression"] }

tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
