[package]
name = "otel-metrics"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
viz = { path = "../../../viz", features = ["otel-metrics", "otel-prometheus"] }

tokio = { version = "1.0", features = [
  "rt-multi-thread",
  "macros",
] }
opentelemetry = { version = "0.18.0", default-features = false, features = ["metrics"]}
