[package]
name = "session"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
viz = { path = "../../viz", features = ["session"] }
sessions = { version = "0.3.4", features = ["memory"] }

tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
nano-id = "0.2"
