[package]
name = "smol-example"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
viz-smol.workspace = true

# smol
async-net.workspace = true
smol-macros = "0.1"
macro_rules_attribute = "0.2"
