[package]
name = "graceful-shutdown-example"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
viz.workspace = true

tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
