[package]
name = "viz"
version = "0.1.2"
authors = ["Fangdun Tsai <cfddream@gmail.com>"]
description = "Fast, flexible, minimalist web framework for Rust"
homepage = "https://viz.rs"
documentation = "https://docs.rs/viz"
repository = "https://github.com/viz-rs/viz"
keywords = ["viz", "http", "web", "framework", "async"]
categories = [
  "asynchronous",
  "network-programming",
  "web-programming::http-server",
]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2021"

[features]
default = ["tcp", "http1"]

sse = ["viz-core/sse"]
ws = ["viz-core/ws"]
fs = ["viz-core/fs"]
tcp = ["hyper/tcp"]
uds = ["hyper/stream", "tokio/net"]
http1 = ["hyper/http1"]
http2 = ["hyper/http2"]
tls = ["tokio-rustls", "tokio/io-util", "rustls-pemfile"]

middleware = []

middleware-full = [
  "middleware",
  "middleware-logger",
  "middleware-recover",
  "middleware-timeout",
  "middleware-request-nanoid",
  "middleware-auth",
  "middleware-cors",
  "middleware-cookies",
  "middleware-sessions",
  "middleware-compression",
]

middleware-logger = ["viz-middleware/logger"]
middleware-recover = ["viz-middleware/recover"]
middleware-timeout = ["viz-middleware/timeout"]

middleware-request-nanoid = ["viz-middleware/request-nanoid"]
middleware-request-uuid = ["viz-middleware/request-uuid"]

middleware-auth = ["viz-middleware/auth"]
middleware-cors = ["viz-middleware/cors"]
middleware-cookies = ["viz-middleware/cookies"]

middleware-sessions = ["viz-middleware/sessions"]
middleware-sessions-memory = ["viz-middleware/sessions-memory"]
middleware-sessions-redis = ["viz-middleware/sessions-redis"]

middleware-jwt = ["viz-middleware/jwt"]
middleware-jwt-param = ["viz-middleware/jwt-param"]
middleware-jwt-query = ["viz-middleware/jwt-query"]
middleware-jwt-cookie = ["viz-middleware/jwt-cookie"]
middleware-jwt-header = ["viz-middleware/jwt-header"]

middleware-compression = ["viz-middleware/compression"]
middleware-compression-gzip = ["viz-middleware/compression-gzip"]
middleware-compression-brotli = ["viz-middleware/compression-brotli"]
middleware-compression-deflate = ["viz-middleware/compression-deflate"]

[dependencies]
viz-core = { path = "../viz-core", version = "0.1.2" }
viz-router = { path = "../viz-router", version = "0.1.2" }
viz-utils = { path = "../viz-utils", version = "0.1.2" }
viz-middleware = { path = "../viz-middleware", version = "0.1.2", default-features = false, optional = true }

hyper = { version = "0.14", features = ["server"] }

tokio = { version = "1.13", default-features = false, features = ["net"], optional = true }
tokio-rustls = { version = "0.23", optional = true }
rustls-pemfile = { version = "1.0", optional = true }
