[package]
name = "websocket-chat"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
viz = { path = "../../viz", features = ["websocket"] }

tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }
futures-util.workspace = true
